@echo off
echo Running all tests...

echo Building images...
call build.bat

echo Deploying to test environment...
call deploy.bat

echo Waiting for services to be ready...
timeout /t 30 /nobreak >nul

echo Running unit tests...
cd backend
npm test

echo Running integration tests...
npm run test -- --testPathPattern=integration

echo Running end-to-end tests...
cd ..\e2e-tests
kubectl apply -f test-runner.yaml -n presence-test

echo Waiting for E2E tests to complete...
timeout /t 60 /nobreak >nul

echo Getting test results...
kubectl logs -l app=e2e-test -n presence-test

echo Cleaning up test environment...
kubectl delete namespace presence-test --ignore-not-found=true

echo Tests completed!