apiVersion: v1
kind: Service
metadata:
  name: presence-frontend-service
spec:
  type: NodePort
  selector:
    app: presence-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      # NodePort will be automatically assigned by Kubernetes, typically in the 30000-32767 range
