{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "attendance.fullname" . }}-backend
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "attendance.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "attendance.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "attendance.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "attendance.fullname" . }}
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: DATABASE_URL
              value: {{ .Values.backend.env.DATABASE_URL | quote }}
            - name: WHATSAPP_ENABLED
              value: {{ .Values.backend.env.WHATSAPP_ENABLED | quote }}
            - name: TWILIO_ACCOUNT_SID
              value: {{ .Values.backend.env.TWILIO_ACCOUNT_SID | quote }}
            - name: TWILIO_AUTH_TOKEN
              value: {{ .Values.backend.env.TWILIO_AUTH_TOKEN | quote }}
            - name: TWILIO_FROM_NUMBER
              value: {{ .Values.backend.env.TWILIO_FROM_NUMBER | quote }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "attendance.fullname" . }}-backend
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "attendance.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "attendance.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
{{- if .Values.backend.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "attendance.fullname" . }}-backend
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "attendance.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  {{- with .Values.backend.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.backend.ingress.className }}
  ingressClassName: {{ .Values.backend.ingress.className }}
  {{- end }}
  rules:
    {{- range .Values.backend.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "attendance.fullname" $ }}-backend
                port:
                  number: {{ $.Values.backend.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}
