{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    {{- include "attendance.labels" . | nindent 4 }}
    name: {{ .Values.namespace.name }}
{{- end }}
