apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "presence.fullname" . }}-api
  labels:
    {{- include "presence.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "presence.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "presence.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.36.1
          command: ['sh', '-c', 'until nc -z {{ printf "%s-%s" .Release.Name "postgresql" }} 5432; do echo waiting for db; sleep 2; done;']
          env:
            - name: DB_HOST
              value: {{ printf "%s-%s" .Release.Name "postgresql" }}
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: DB_HOST
              value: {{ printf "%s-%s" .Release.Name "postgresql" }}
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-%s" .Release.Name "postgresql" }}
                  key: postgres-password
            - name: DB_NAME
              value: "presence"
          # Add readiness and liveness probes
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
