apiVersion: v1
kind: Service
metadata:
  name: {{ include "presence.fullname" . }}-manager
  labels:
    {{- include "presence.labels" . | nindent 4 }}
    app.kubernetes.io/component: manager
spec:
  type: {{ .Values.manager.service.type }}
  ports:
    - port: {{ .Values.manager.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "presence.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: manager
