apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "presence.fullname" . }}-manager
  labels:
    {{- include "presence.labels" . | nindent 4 }}
    app.kubernetes.io/component: manager
spec:
  replicas: {{ .Values.manager.replicaCount }}
  selector:
    matchLabels:
      {{- include "presence.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: manager
  template:
    metadata:
      labels:
        {{- include "presence.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: manager
    spec:
      containers:
        - name: manager
          image: "{{ .Values.manager.image.repository }}:{{ .Values.manager.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.manager.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
